export const juz = [
  {
    number: 1,
    name: 'Alif Lam Mim',
    arabicName: 'ٱلٓمّٓ',
    meaning: 'Alif, Lam, Meem',
    ayatCount: 148,
  },
  {
    number: 2,
    name: 'Sayaqool',
    arabicName: 'سَيَقُولُ',
    meaning: 'He will say',
    ayatCount: 111,
  },
  {
    number: 3,
    name: 'Tilka Ar-Rusul',
    arabicName: 'تِلْكَ ٱلرُّسُلُ',
    meaning: 'Those are the Messengers',
    ayatCount: 126,
  },
  {
    number: 4,
    name: 'Lan Tanaloo',
    arabicName: 'لَنْ تَنَالُوا۟',
    meaning: 'Never will you attain',
    ayatCount: 131,
  },
  {
    number: 5,
    name: 'Wa Al-Muhsanat',
    arabicName: 'وَٱلْمُحْصَنَاتُ',
    meaning: 'And the chaste women',
    ayatCount: 124,
  },
  {
    number: 6,
    name: 'La Yuhibbullah',
    arabicName: 'لَا يُحِبُّ ٱللَّهُ',
    meaning: 'Allah does not like',
    ayatCount: 128,
  },
  {
    number: 7,
    name: 'Wa Iza Samiu',
    arabicName: 'وَإِذَا سَمِعُوا۟',
    meaning: 'And when they hear',
    ayatCount: 149,
  },
  {
    number: 8,
    name: 'Wa Al-A\'raf',
    arabicName: 'وَٱلْأَعْرَافِ',
    meaning: 'And the Heights',
    ayatCount: 149,
  },
  {
    number: 9,
    name: 'Iqtaraba',
    arabicName: 'ٱقْتَرَبَ',
    meaning: 'Has drawn near',
    ayatCount: 129,
  },
  {
    number: 10,
    name: 'Wa A\'lamu',
    arabicName: 'وَٱعْلَمُوا۟',
    meaning: 'And know',
    ayatCount: 123,
  },
  {
    number: 11,
    name: 'Yatazeroon',
    arabicName: 'يَعْتَذِرُونَ',
    meaning: 'They make excuses',
    ayatCount: 151,
  },
  {
    number: 12,
    name: 'Wa Mamin Da\'abah',
    arabicName: 'وَمَا مِن دَآبَّةٍ',
    meaning: 'And there is no creature',
    ayatCount: 127,
  },
  {
    number: 13,
    name: 'Wa Ma Ubarru',
    arabicName: 'وَمَا أُبَرِّئُ',
    meaning: 'And I do not absolve',
    ayatCount: 154,
  },
  {
    number: 14,
    name: 'Rubama',
    arabicName: 'رُبَمَا',
    meaning: 'Perhaps',
    ayatCount: 128,
  },
  {
    number: 15,
    name: 'Subhana Alladhi',
    arabicName: 'سُبْحَٰنَ ٱلَّذِى',
    meaning: 'Exalted is He',
    ayatCount: 185,
  },
  {
    number: 16,
    name: 'Qala Alam',
    arabicName: 'قَالَ أَلَمْ',
    meaning: 'He said, did not',
    ayatCount: 184,
  },
  {
    number: 17,
    name: 'Iqtaraba Lin-Nas',
    arabicName: 'ٱقْتَرَبَ لِلنَّاسِ',
    meaning: 'The time has come near for mankind',
    ayatCount: 183,
  },
  {
    number: 18,
    name: 'Qad Aflaha',
    arabicName: 'قَدْ أَفْلَحَ',
    meaning: 'Certainly succeeded',
    ayatCount: 118,
  },
  {
    number: 19,
    name: 'Wa Qala Alladhina',
    arabicName: 'وَقَالَ ٱلَّذِينَ',
    meaning: 'And those who said',
    ayatCount: 137,
  },
  {
    number: 20,
    name: 'Amman Khalaqa',
    arabicName: 'أَفَمَنۡ خَلَقَ',
    meaning: 'Is He who created',
    ayatCount: 135,
  },
  {
    number: 21,
    name: 'Utlu Ma Oohiya',
    arabicName: 'ٱتْلُ مَا أُوحِىَ',
    meaning: 'Recite what has been revealed',
    ayatCount: 178,
  },
  {
    number: 22,
    name: 'Wa Man Yaqnut',
    arabicName: 'وَمَن يَقْنُتْ',
    meaning: 'And whoever devoutly obeys',
    ayatCount: 169,
  },
  {
    number: 23,
    name: 'Wa Mali',
    arabicName: 'وَمَالِىَ',
    meaning: 'And what is [wrong] with me',
    ayatCount: 181,
  },
  {
    number: 24,
    name: 'Faman Azlamu',
    arabicName: 'فَمَنْ أَظْلَمُ',
    meaning: 'Who is more unjust',
    ayatCount: 175,
  },
  {
    number: 25,
    name: 'Ilayhi Yuraddu',
    arabicName: 'إِلَيْهِ يُرَدُّ',
    meaning: 'To Him is returned',
    ayatCount: 227,
  },
  {
    number: 26,
    name: 'Ha Mim',
    arabicName: 'حٰمٓ',
    meaning: 'Ha Meem (disjointed letters)',
    ayatCount: 227,
  },
  {
    number: 27,
    name: 'Qala Fama Khatbukum',
    arabicName: 'قَالَ فَمَا خَطْبُكُم',
    meaning: 'He said: What is your affair',
    ayatCount: 195,
  },
  {
    number: 28,
    name: 'Qad Sami Allah',
    arabicName: 'قَدْ سَمِعَ ٱللَّهُ',
    meaning: 'Allah has certainly heard',
    ayatCount: 171,
  },
  {
    number: 29,
    name: 'Tabaraka Alladhi',
    arabicName: 'تَبَارَكَ ٱلَّذِى',
    meaning: 'Blessed is He',
    ayatCount: 431,
  },
  {
    number: 30,
    name: 'Amma',
    arabicName: 'عَمَّ',
    meaning: 'About what',
    ayatCount: 564,
  },
];